# Generated by Django 5.2 on 2025-05-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moviename', models.CharField(max_length=200)),
                ('Director', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
                ('Duration_minutes', models.PositiveIntegerField()),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
